const { Router } = require('express')
const auth = require('./auth.route')
const user = require('./user.route')
const regenttype = require('./regenttype.route')
const regent = require('./regent.route')
const product = require('./product.route')
const fertEnm = require('./fertilizeramendmentcategory.route')
const chemicalelement = require('./chemicalelement.route')
const measurementunit = require('./measurementunit.route')
const analysismethod = require('./analysismethod.route')
const crop = require('./crop.route')
const applicationway = require('./applicationway.route')
const packingtype = require('./packingtype.route')
const rawmaterial = require('./rawmaterial.route')
const fertilizeramendmentType = require('./fertilizeramendmenttype.route')
const manufacturer = require('./manufacturer.route')
const procedures = require('./procedure.route')
const formulationType = require('./formulationType.route')
const physicalstate = require('./physicalstate.route')
const pesticidesclassification = require('./pesticidesclassification.route')
const pesticidestypes = require('./pesticidestypes.route')
const taxokingdom = require('./taxokingdom.route')
const taxodivision = require('./taxodivision.route')
const taxofamily = require('./taxofamily.route')
const plaguetype = require('./plaguetype.route')
const taxoorder = require('./taxoorder.route')
const taxoclass = require('./taxoclass.route')
const plagueclass = require('./plagueclass.route')

const router = Router()
router.use('/auth', auth)
router.use('/users', user)
router.use('/regenttypes', regenttype)
router.use('/regent', regent)
router.use('/products', product)
router.use('/fertenm', fertEnm)
router.use('/chemicalelement', chemicalelement)
router.use('/measurementunit', measurementunit)
router.use('/analysismethod', analysismethod)
router.use('/crop', crop)
router.use('/applicationway', applicationway)
router.use('/packingtype', packingtype)
router.use('/rawmaterial', rawmaterial)
router.use('/fertilizeramendmentType', fertilizeramendmentType)
router.use('/manufacturer', manufacturer)
router.use('/procedures', procedures)
router.use('/formulationType', formulationType)
router.use('/physicalstate', physicalstate)
router.use('/pesticidesclassification', pesticidesclassification)
router.use('/pesticidestypes', pesticidestypes)
router.use('/taxokingdom', taxokingdom)
router.use('/taxodivision', taxodivision)
router.use('/taxofamily', taxofamily)
router.use('/plaguetype', plaguetype)
router.use('/taxoorder', taxoorder)
router.use('/taxoclass', taxoclass)
router.use('/plagueclass', plagueclass)

module.exports = router